### ISSUE TITLE
Better upload validation

### ISSUE THREAD

**Issue by ngparas** [UptakeOpenSource/cran-server#10]
server.py relies on the R CMD build tarball naming convention when receiving uploads and doesn't do much in the way of validation. We should at least check that uploads conform to this convention

**Comment by ntdef** [comment]
We could also read the `DESCRIPTION` file out of the tarball on upload. That way, we don't have to rely on a particular naming convention.

**Comment by ngparas** [comment]
yeah thats better, especially since we need to pull the `DESCRIPTION` out anyway

**Comment by ntdef** [comment]
This is done in the version at HEAD.
