### ISSUE TITLE
Github pages support

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/cran-server#32]
I hooked up our `gh-pages` to look at the `docs/` folder on `master`. My suspicions were confirmed...markdowns don't get automagically rendered there.

https://uptakeopensource.github.io/cran-server/why_cran_server.md opens as a download link :/

I think we need to render the HTML equivalent of that file and check it into the repo in the `docs/` folder. Thoughts?

**Comment by ntdef** [comment]
@jameslamb easiest way to do this is to setup Jekyll, which GHub automatically runs under the hood.. I can show you tomorrow.

**Comment by ntdef** [comment]
This is done.
